ManagementSystem_Attack/ManagementSystem/Controllers/UploadFileController.cs
using ManagementSystem.Controllers.Base;
using ManagementSystem.Models;
using ManagementSystem.Models.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagementSystem.Controllers
{
    public class UploadFileController : BaseController
    {
        public ActionResult SMS_Upload()
        {
            Session.Remove("SMS_UPLOAD");
            UploadModel model = new UploadModel();
            //  SMSUpload serv = new SMSUpload();

            model.dtoData = new SMSUploadModel();
            model.valid = false;
            model.notValid = false;
            model.alreadyUpload = false;
            model.continueProcess = false;
            model.resultSuccess = false;
            model.resultError = false;
            model.message = "";


            return View(model);
        }

        [HttpPost]
        public JsonResult SMS_PreviewData(UploadModel model)
        {
            try
            {
                foreach (string item in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[item] as HttpPostedFileBase;
                    SMSUpload serv = new SMSUpload();
                   
                    int filterRecords = 0;
                    bool isValid = true;
                    List<SMSUploadModel> result = serv.readSmsFromFile(_db, file, out isValid);
                    Session.Add("SMS_UPLOAD", result);
                    filterRecords = (result == null ? 0 : result.Count());

                    model.lstData = new List<SMSUploadModel>();
                    model.isValid = isValid;
                    model.alreadyUpload = true;
                    model.valid = model.isValid;
                    model.notValid = !model.valid;
                    model.totalRecord = filterRecords;
                    return Json(new JSonResultService() { status = 200, message = "", dataResult = model }, JsonRequestBehavior.DenyGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new JSonResultService() { status = 500, message = ex.Message.ToString(), dataResult = null }, JsonRequestBehavior.DenyGet);
            }

            return Json(new JSonResultService() { status = 500, message = "Internal Error", dataResult = model }, JsonRequestBehavior.DenyGet);
        }


        public JsonResult SMS_PreviewData_Paging(UploadPagingModel model)
        {
            try
            {
                if (model.continueProcess)
                {
                    List<SMSUploadModel> result = new List<SMSUploadModel>();
                    if (Session["SMS_UPLOAD"] != null)
                    {
                        result = (List<SMSUploadModel>)Session["SMS_UPLOAD"];
                    }

                    model.resultSuccess = false;
                    model.resultError = false;
                    model.message = "";
                    model.alreadyUpload = true;


                    if (result != null && result.Count() > 0)
                    {
                        return Json(new
                        {
                            draw = model.draw,
                            recordsTotal = result.Count(),
                            recordsFiltered = result.Count(),
                            data = result.OrderByDescending(s => s.prop_flagstat).ThenByDescending(s => s.createTime).Skip(model.start).Take(model.length)
                        });
                    }
                    else
                    {
                        return Json(new
                        {

                            draw = model.draw,
                            recordsTotal = 0,
                            recordsFiltered = 0,
                            data = new LinkedList<SMSUploadModel>()
                        });
                    }
                }
                else
                {
                    return Json(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,
                        recordsFiltered = 0,
                        data = new LinkedList<SMSUploadModel>()
                    });
                }
            }
            catch (Exception ex)
            {
                return Json(new JSonResultService() { status = 500, message = ex.Message.ToString(), dataResult = null }, JsonRequestBehavior.DenyGet);
            }
        }


        [HttpPost]
        public JsonResult SMS_saveUploadData(UploadModel model)
        {
            try
            {
                List<SMSUploadModel> sessionModel = new List<SMSUploadModel>();
                if (Session["SMS_UPLOAD"] == null)
                {
                    return Json(new JSonResultService() { status = 500, message = "ไม่สามารถบันทึกข้อมูลได้ กรุณาทำรายการอีกครั้ง", dataResult = null }, JsonRequestBehavior.DenyGet);
                }
                sessionModel = (List<SMSUploadModel>)Session["SMS_UPLOAD"];

                if (sessionModel == null)
                {
                    return Json(new JSonResultService() { status = 500, message = "Session model is null!!!", dataResult = null }, JsonRequestBehavior.DenyGet);
                }


                SMSUpload serv = new SMSUpload();
             
                serv.uploadSMSData(_db, _userInfo, sessionModel);
                Session.Remove("SMS_UPLOAD");

                model.resultSuccess = true;
                model.resultError = false;
                model.message = "นำข้อมูลเข้าเรียบร้อยค่ะ";
                model.alreadyUpload = false;

                return Json(new JSonResultService() { status = 200, message = "นำข้อมูลเข้าเรียบร้อยค่ะ", dataResult = model }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception ex)
            {
                model.resultSuccess = false;
                model.resultError = true;
                model.message = ex.Message.ToString();
                return Json(new JSonResultService() { status = 500, message = ex.Message.ToString(), dataResult = model }, JsonRequestBehavior.DenyGet);
            }

        }


        // ==========================================
        public ActionResult COUPON_Upload()
        {
            Session.Remove("COUPON_UPLOAD");
            UploadModel model = new UploadModel();
           
            model.valid = false;
            model.notValid = false;
            model.alreadyUpload = false;
            model.continueProcess = false;
            model.resultSuccess = false;
            model.resultError = false;
            model.message = "";


            return View(model);
        }

        [HttpPost]
        public JsonResult COUPON_PreviewData(UploadModel model)
        {
            try
            {
                foreach (string item in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[item] as HttpPostedFileBase;
                    SMSUpload serv = new SMSUpload();

                    int filterRecords = 0;
                    bool isValid = true;
                    List<CouponUploadModel> result = serv.readCouponFromFile(_db, file, out isValid);
                    Session.Add("COUPON_UPLOAD", result);
                    filterRecords = (result == null ? 0 : result.Count());

                    model.lstCouponData = new List<CouponUploadModel>();
                    model.isValid = isValid;
                    model.alreadyUpload = true;
                    model.valid = model.isValid;
                    model.notValid = !model.valid;
                    model.totalRecord = filterRecords;
                    return Json(new JSonResultService() { status = 200, message = "", dataResult = model }, JsonRequestBehavior.DenyGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new JSonResultService() { status = 500, message = ex.Message.ToString(), dataResult = null }, JsonRequestBehavior.DenyGet);
            }

            return Json(new JSonResultService() { status = 500, message = "Internal Error", dataResult = model }, JsonRequestBehavior.DenyGet);
        }


        public JsonResult COUPON_PreviewData_Paging(UploadPagingModel model)
        {
            try
            {
                if (model.continueProcess)
                {
                    List<CouponUploadModel> result = new List<CouponUploadModel>();
                    if (Session["COUPON_UPLOAD"] != null)
                    {
                        result = (List<CouponUploadModel>)Session["COUPON_UPLOAD"];
                    }

                    model.resultSuccess = false;
                    model.resultError = false;
                    model.message = "";
                    model.alreadyUpload = true;


                    if (result != null && result.Count() > 0)
                    {
                        return Json(new
                        {
                            draw = model.draw,
                            recordsTotal = result.Count(),
                            recordsFiltered = result.Count(),
                            data = result.OrderByDescending(s => s.prop_flagstat).ThenByDescending(s => s.createTime).Skip(model.start).Take(model.length)
                        });
                    }
                    else
                    {
                        return Json(new
                        {

                            draw = model.draw,
                            recordsTotal = 0,
                            recordsFiltered = 0,
                            data = new LinkedList<CouponUploadModel>()
                        });
                    }
                }
                else
                {
                    return Json(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,

ManagementSystem_Attack/ManagementSystem/Views/UploadFile/COUPON_Upload.cshtml
@model ManagementSystem.Models.UploadModel

@{
    ViewBag.Title = "Coupon";
}
<style type="text/css">
    .table-wrap {
        height: 80px;
        overflow-y: auto;
    }
</style>
<div class="normalheader">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>
            <h2 class="font-light m-b-xs">
                Import Coupon
            </h2>
        </div>
    </div>
</div>



<div id="viewContent" class="content">


    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel  hblue">
                <div class="panel-body2 hblue">
                    @using (Ajax.BeginForm("COUPON_PreviewData", "UploadFile", null, new AjaxOptions { UpdateTargetId = "uploadResultContainer" }, new { id = "form-ajax" }))
                    {
                        <div id="myForm">
                            <div class="form-group">
                                <label class="col-md-12 col-sm-12 col-12  control-label">Select Data to upload:</label>
                            </div>

                            <div class="form-group">
                                <small><code>*ระบบจะอ่านเฉพาะข้อมูลจาก Sheet ที่มีชื่อว่า [My Sheet] เท่านั้น</code></small>
                            </div>
                            <div class="form-group">
                                <input id="input-709" name="kartik-input-709[]" type="file" multiple class="file-loading" accept=".xls,.xlsx">
                                <div id="kv-error-1" style="margin-top: 10px; display: none"></div>
                                <div id="kv-success-1" class="alert alert-success fade in" style="margin-top: 10px; display: none"></div>
                            </div>

                            <div class="widget-body ">
                                <div class="form-group" id="msg-info-succ" data-bind="visible: myObject.resultSuccess">
                                    <div class="alert alert-success ">
                                        <i class="fa-fw fa fa-check"></i>
                                        <strong>Success!</strong><span data-bind="text: myObject.message"></span>
                                    </div>
                                </div>
                                <div class="form-group" id="msg-info-error" data-bind="visible: myObject.resultError">
                                    <div class="alert alert-danger ">
                                        <i class="fa-fw fa fa-times"></i>
                                        <strong>Error!</strong><span data-bind="text: myObject.message"></span>
                                    </div>
                                </div>

                                <div id="uploadResultContainer" data-bind="visible: myObject.alreadyUpload">
                                    <div class="form-group text-right" data-bind="visible: myObject.valid">
                                        <button id="btn-save" type="button" class="btn btn-primary btn-sm ladda-button" data-style="zoom-in">
                                            <i class="fa fa-save"></i> Save
                                        </button>
                                    </div>
                                    <div class="form-group" data-bind="visible: myObject.notValid">
                                        <div class="alert alert-danger ">
                                            <i class="fa-fw fa fa-times"></i>
                                            <strong>Error!</strong>    <span>พบข้อผิดพลาด</span>
                                        </div>
                                    </div>
                                    <div class="panel-body table-responsive m-t table-bordered">
                                        <table id="table-list" class="table table-striped table-bordered" style="font-size: 0.8em;" width="100%">
                                            <thead>
                                                <tr>
                                                    <th class="small"><span>Campaign ID</span></th>
                                                    <th class="small"><span>Create Date</span></th>
                                                    <th class="small"><span>Tel</span></th>
                                                    <th class="small"><span>Firstname</span></th>
                                                    <th class="small"><span>Lastname</span></th>
                                                    <th class="small"><span>Receipt No</span></th>
                                                    <th class="small"><span>Error</span></th>
                                                    <th class="small"><span>Message/ข้อความ</span></th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade hmodal-danger" id="modal-error" tabindex="999" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="color-line"></div>
                <div class="modal-header">
                    <h4 class="modal-title">Error</h4>
                </div>
                <div class="modal-body">
                    <label id="lblerror"></label>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script type="text/javascript">
    $(function () {
        var dataupload;
        var table = null;
        function ViewModel(data) {
            self.myObject = this;
            ko.mapping.fromJS(data, {}, self.myObject);

        };

        var model = @Html.Raw(Json.Encode(Model));
        ko.applyBindings(new ViewModel(model));

        $("#input-709").fileinput({
            uploadUrl: '@Url.Action("COUPON_PreviewData", "UploadFile")', // server upload action
            uploadAsync: true,
            showPreview: false,
            allowedFileExtensions: ['xls', 'xlsx'],
            maxFileCount: 1,
            elErrorContainer: '#kv-error-1'
        }).on('filebatchpreupload', function (event, data, id, index) {
        }).on('fileuploaded', function (event, data, id, index) {

            self.myObject.continueProcess(true);

            if (data.response.status == 200) {

                $('#kv-success-1').html('<h4>Total Record: ' + data.response.dataResult.totalRecord + '</h4>').hide();
                $('#kv-success-1').fadeIn('slow');

                self.myObject.alreadyUpload(data.response.dataResult.alreadyUpload);
                self.myObject.valid(data.response.dataResult.valid);
                self.myObject.notValid(data.response.dataResult.notValid);

                self.myObject.resultSuccess(data.response.dataResult.resultSuccess);
                self.myObject.resultError(data.response.dataResult.resultError);
                self.myObject.message(data.response.dataResult.message);



                dataupload = data.response.dataResult;

                $("#btn-save").on('click', function () {
                    bootbox.confirm("ต้องการบันทึกการข้อมูลจากไฟล์ใช่หรือไม่?", function (result) {
                        if (result != null && result == true) {
                            var l = $('#btn-save').ladda();
                            l.ladda('start');
                            setTimeout(function () {
                                $.ajax({
                                    url: '@Url.Action("COUPON_saveUploadData", "UploadFile")',
                                    type: "POST",
                                    data: JSON.stringify({ 'model': dataupload }),
                                    dataType: "json",
                                    contentType: "application/json; charset=utf-8",
                                    success: function (result) {
                                        self.myObject.resultSuccess(result.dataResult.resultSuccess);
                                        self.myObject.resultError(result.dataResult.resultError);
                                        self.myObject.message(result.dataResult.message);
                                        self.myObject.alreadyUpload(result.dataResult.alreadyUpload);
                                        l.ladda('stop');
                                    },
                                    error: function (result) {
                                        self.myObject.resultError(result.dataResult.resultError);
                                        self.myObject.message(result.dataResult.message);
                                        self.myObject.alreadyUpload(result.dataResult.alreadyUpload);
                                        l.ladda('stop');
                                    }
                                });


                            }, 500)



                        }
                    });

                });


                if (table != null) {
                    table.clear().draw();
                    table.ajax.reload(null, false);  //Reload Ajax When Search Click

                    return;
                }
            }
            else {
                $("#lblerror").html(data.response.message);
                $('#modal-error').modal('show');
            }
        });

        if (table != null) {
            table.fnReloadAjax(); //Reload Ajax When Search Click
            return;
        }


        table = $('#table-list').DataTable({
            "processing": true,
            "serverSide": true,
            "ordering": true,
            "searching": false,
            "stateSave": false,
            "lengthChange": true,
            "pageLength": 10,
            "ajax": {
                url: _app.baseURL + 'UploadFile/COUPON_PreviewData_Paging',
                type: 'POST',
                data: function (d) {
                    var formObj = ko.toJSON(self.myObject);
                    formObj = JSON.parse(formObj);
                    $.extend(d,formObj);
                }
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
            "columns": [
                { "data": "campaignId", "orderable": false},
                { "data": "createTime" , "orderable": false},
                { "data": "tel" , "orderable": false},
                { "data": "firstname", "orderable": false},
                { "data": "lastname" , "orderable": false},
                { "data": "recNo" , "orderable": false},
                {
                    "orderable": false,
                    "render": function (data, type, full, meta) {
                        if (full.prop_flagstat == false) {
                            return '<span class="label label-danger">Error</span>';
                        } else {
                            return '<span ></span>';
                        }
                    }
                },
                { "data": "prop_errorMsg", "orderable": false },

            ]
        });


    });
    </script>


}